In [ ]:
# To install Jupyter, go to the command line (not inside of Python)
# and type

pip3 install -U jupyter
or
pip install -U jupyter

# then you should be able to type

jupyter notebook



In [1]:
# REPL -- read, eval, print loop

print('Hello, world!')  # shift + enter together == run the cell

Hello, world!


In [2]:
print('Hello, world!')
print('Hello, again!')

Hello, world!
Hello, again!


In [6]:
x = 100

In [7]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

In [8]:
# shift+enter runs a cell

In [9]:
# "magic" commands

# if the command starts with %, Jupyter "steals" it and runs it itself
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2019-dec'

In [10]:
# ! before a command runs it in a shell

In [11]:
%whos  

Variable   Type    Data/Info
----------------------------
x          int     100


In [13]:
y = [10, 20, 30]

z = {'a':1, 'b':2, 'c':3}

def hello(name):
    return f'Hello, {name}'

In [14]:
%whos

Variable   Type        Data/Info
--------------------------------
hello      function    <function hello at 0x10fbacd40>
x          int         100
y          list        n=3
z          dict        n=3


In [15]:
%magic

In [16]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [17]:
print(x * 2)

200


In [18]:
# only in Jupyter, the final expression in a cell is returned
x

100

In [19]:
x*2

200

In [20]:
2+2
3+3
4+4

8

In [22]:
s = 'abcde'

In [23]:
s.upper()

'ABCDE'

In [24]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

name = input("Enter your name: ").strip()
print(f'Hello, {name}')

Enter your name: Reuven
Hello, Reuven


In [ ]:
# from the command line, install NumPy with
# pip3 install -U numpy 

# import numpy   # don't do this!

# the below is super-standard in data science
import numpy as np

In [25]:
# the below line loads NumPy as np (and does other things, too)
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [27]:
np.ndarray    # NumPy's n-dimensional array

numpy.ndarray

In [29]:
# don't run np.ndarray directly

# instead, use np.array!
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [30]:
type(a)

numpy.ndarray

In [31]:
a[0]

10

In [32]:
a[2]

30

In [33]:
a[-1]

50

In [34]:
a

array([10, 20, 30, 40, 50])

In [35]:
30 in a

True

In [36]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [37]:
a

array([10, 20, 30, 40, 50])

In [38]:
# simplest is np.array
np.array([10, 20, 30, 40, 50])



array([10, 20, 30, 40, 50])

In [40]:
# random integers -- use np.random.randint(max, min, count)
np.random.randint(0, 100, 10)

array([62,  6, 93,  3, 20, 58,  1, 77, 45, 35])

In [41]:
# random floats between 0-1 -- use np.random.rand(count)
np.random.rand(10)

array([0.10829865, 0.24817243, 0.46661636, 0.69170322, 0.21394568,
       0.70065355, 0.25283911, 0.55662296, 0.73601991, 0.23784385])

In [44]:
# I want a NumPy array with all numbers from 10-20
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10, 30, 4)

array([10, 14, 18, 22, 26])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
a

array([10, 20, 30, 40, 50])

In [50]:
# arrays are mutable!
a[2] = 12345
a

array([   10,    20, 12345,    40,    50])

In [51]:
# (1) Create a NumPy array with the integers from your birthdate (year,
#     month, and day)

a = np.array([1970, 7, 14])

In [52]:
# (2) Retrieve the year.
a[0]

1970

In [53]:
# (3) Replace the year with the current year.
a[0] = 2019
a

array([2019,    7,   14])

In [54]:
# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the 8th number in this array?  What is the 15th?

a = np.arange(567, 890, 3)
a[8]


591

In [55]:
a[15]

612

In [56]:
mylist = [10, 20, 30, 40, 50]
mylist + 60

TypeError: can only concatenate list (not "int") to list

In [57]:
mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [58]:
a = np.array([10, 20, 30 ,40, 50])
a + a

array([ 20,  40,  60,  80, 100])

In [59]:
# adding two arrays means adding each element at the same index

a - a

array([0, 0, 0, 0, 0])

In [60]:
a * a

array([ 100,  400,  900, 1600, 2500])

In [61]:
a / a

array([1., 1., 1., 1., 1.])

In [62]:
b = np.array([10, 20, 30, 40, 50, 60])

a + b

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [63]:
a

array([10, 20, 30, 40, 50])

In [65]:
a + 3 # this 'broadcasts' the scalar value and adds it to each in a

array([13, 23, 33, 43, 53])

In [66]:
a - 3

array([ 7, 17, 27, 37, 47])

In [67]:
a * 3

array([ 30,  60,  90, 120, 150])

In [68]:
a / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [69]:
a ** 3

array([  1000,   8000,  27000,  64000, 125000])

In [70]:
a % 3

array([1, 2, 0, 1, 2])

In [71]:
a

array([10, 20, 30, 40, 50])

In [72]:
# NumPy array methods:

a.sum()

150

In [73]:
a.mean()

30.0

In [74]:
a.std()

14.142135623730951

In [75]:
a.min()

10

In [76]:
a.max()

50

In [79]:
a.size  # not a method -- data giving us the size

5

In [82]:
# multiply the result from np.random.rand, and get
# numbers from 0 to that multiplied value

np.random.rand(10) * 100

array([10.69046194, 64.26513365, 28.10584285, 12.84197429, 30.90030687,
       39.10297485, 34.56071006, 96.01627624, 88.58263931, 17.35199359])

In [83]:
np.ones(10) * 8

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [84]:
np.zeros(10) + 8

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [85]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [86]:
# (1) Create an array of 10 random integers, from 0-100.

a = np.random.randint(0, 100, 10)
a

array([40, 49, 33, 10, 28, 36, 22, 32, 56, 73])

In [87]:
# (2) Find the mean and standard deviation of these numbers.  
a.mean()

37.9

In [88]:
a.std()

16.96732153287607

In [89]:
# (3) Create another array of 10 random integers, from 0-100.
b = np.random.randint(0, 100, 10)
b

array([50, 68, 58, 70, 89, 49, 71, 89, 30, 54])

In [90]:
# (4) Create a new 2-element array whose elements are
#     the average (mean) of those from exercises 1 and 3

c = np.array([a.mean(), b.mean()])
c

array([37.9, 62.8])

In [91]:
# (5) Create an array of 10 random floats, from 0-100.
a = np.random.rand(10) * 100
a

array([30.44166337, 79.58796334,  5.65226957, 54.31853198, 36.58045017,
       19.59407182, 43.14154103, 40.22547496, 18.49171147, 23.77969494])

In [92]:
# (6) We would expect the mean to be approaximately 50. 
#     Is it?  What's the standard deviation?
a.mean()

35.18133726559421

In [98]:
a = np.random.rand(100000) * 100
a.mean()

49.99103388595718

In [99]:
a.std()

28.870658854398407

In [100]:
# (7) What are the min and max values?
a.min()

0.0007180047562949099

In [101]:
a.max()

99.9988532801397

In [102]:
a = np.random.randint(0, 100, 10)
a

array([60, 69, 80, 48, 67, 89, 73, 64, 98, 92])

In [103]:
a[2]

80

In [104]:
a[6]

73

In [105]:
np.array([a[2], a[6]])

array([80, 73])

In [106]:
# fancy indexing
a[ [2, 6] ]

array([80, 73])

In [107]:
a

array([60, 69, 80, 48, 67, 89, 73, 64, 98, 92])

In [108]:
a[ [2, 6] ] = 1234
a

array([  60,   69, 1234,   48,   67,   89, 1234,   64,   98,   92])

In [109]:
a[ [2,3,2,3,2,3] ]

array([1234,   48, 1234,   48, 1234,   48])

In [110]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [111]:
a[2]

30

In [112]:
a[[2,4]]

array([30, 50])

In [113]:
# mask index -- wherever there is a True value, we get the value from a
a[[True, False, True, False, True]]

array([10, 30, 50])

In [114]:
a[[True, False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2

In [115]:
a

array([10, 20, 30, 40, 50])

In [116]:
a + 3  # this returns a new array; doesn't affect a at all

array([13, 23, 33, 43, 53])

In [117]:
a == 30

array([False, False,  True, False, False])

In [118]:
a < 30

array([ True,  True, False, False, False])

In [119]:
b = a < 30
a[b]   # show me elements of a where b is True (i.e., < 30)

array([10, 20])

In [120]:
a[a<30]  # using a boolean index to retrieve from a

array([10, 20])

In [121]:
a[a>20]

array([30, 40, 50])

In [122]:
a[a<1000]

array([10, 20, 30, 40, 50])

In [123]:
a[a>1000]

array([], dtype=int64)

In [124]:
a = 100
b = 100

a == b   # a.__eq__(b)

True

In [125]:
a

100

In [126]:
a = np.array([10, 20, 30, 40, 50])
a + 5

array([15, 25, 35, 45, 55])

In [127]:
a

array([10, 20, 30, 40, 50])

In [128]:
a += 5    # same as a = a + 5
a

array([15, 25, 35, 45, 55])

In [129]:
a

array([15, 25, 35, 45, 55])

In [130]:
a *= 3

In [131]:
a

array([ 45,  75, 105, 135, 165])

In [132]:
# += -= *= /= **= %= 

In [133]:
a = np.array([10, 15, 20, 25, 30, 35])
a

array([10, 15, 20, 25, 30, 35])

In [134]:
a % 2   # % ("modulus") is the remainder from integer division

array([0, 1, 0, 1, 0, 1])

In [135]:
a[a%2]  # this does NOT give us all odd elements

array([10, 15, 10, 15, 10, 15])

In [136]:
a[a%2 == 1]  # this *DOES* give us all odd elements

array([15, 25, 35])

In [137]:
a[a%2 == 0]  # gives me all even elements

array([10, 20, 30])

In [138]:
a[a%2 == 0] = 9999
a

array([9999,   15, 9999,   25, 9999,   35])

In [143]:
# control-shift-_ splits a cell into two at the current point
# there are menu items to merge cells above/below

# (1) Create an array of 20 random integers from 0 to 100.
a = np.random.randint(0, 100, 20)
a

array([72, 17,  6, 27, 64, 43, 85, 12,  8, 99,  3, 30, 84, 95, 64,  1, 26,
       19, 65, 68])

In [146]:
# (2) Find the largest even number.
a[a%2 == 0].max()

84

In [149]:
# (3) Find the mean of the odd numbers.
a[a%2 == 1].mean()

45.4

In [152]:
# (4) Create a 2-element NumPy array from the 
# first and last odd numbers.
a[a%2 == 1][[0, -1]]

array([17, 65])

In [153]:
# (5) Create an array of 20 floats from 0-1000.
a = np.random.rand(20) * 1000
a

array([705.79754313, 729.21798734, 776.31991389, 192.56154669,
       561.93438959, 112.65675346, 780.78093286,  54.1008814 ,
       596.75184718, 503.85032925,  48.51826974, 689.54483213,
       402.6134912 , 103.36685962, 703.7825231 , 673.87812785,
       414.43131241, 547.89545497, 113.4135059 , 859.88929099])

In [156]:
# (6) Find the items that are less than the mean.

a[a < a.mean()]   # show elements of a < a.mean()


array([192.56154669, 112.65675346,  54.1008814 ,  48.51826974,
       402.6134912 , 103.36685962, 414.43131241, 113.4135059 ])

In [157]:
# (7) Find the items less than mean-std.
a[a < a.mean()-a.std()]



array([192.56154669, 112.65675346,  54.1008814 ,  48.51826974,
       103.36685962, 113.4135059 ])

In [158]:
a[a > a.mean() + a.std()]


array([776.31991389, 780.78093286, 859.88929099])

In [142]:
a = np.random.randint(0, 100, 20)
