In [ ]:
# To install Jupyter, go to the command line (not inside of Python)
# and type

pip3 install -U jupyter
or
pip install -U jupyter

# then you should be able to type

jupyter notebook



In [1]:
# REPL -- read, eval, print loop

print('Hello, world!')  # shift + enter together == run the cell

Hello, world!


In [2]:
print('Hello, world!')
print('Hello, again!')

Hello, world!
Hello, again!


In [6]:
x = 100

In [7]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

In [8]:
# shift+enter runs a cell

In [9]:
# "magic" commands

# if the command starts with %, Jupyter "steals" it and runs it itself
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2019-dec'

In [10]:
# ! before a command runs it in a shell

In [11]:
%whos  

Variable   Type    Data/Info
----------------------------
x          int     100


In [13]:
y = [10, 20, 30]

z = {'a':1, 'b':2, 'c':3}

def hello(name):
    return f'Hello, {name}'

In [14]:
%whos

Variable   Type        Data/Info
--------------------------------
hello      function    <function hello at 0x10fbacd40>
x          int         100
y          list        n=3
z          dict        n=3


In [15]:
%magic

In [16]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [17]:
print(x * 2)

200


In [18]:
# only in Jupyter, the final expression in a cell is returned
x

100

In [19]:
x*2

200

In [20]:
2+2
3+3
4+4

8

In [22]:
s = 'abcde'

In [23]:
s.upper()

'ABCDE'

In [24]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

name = input("Enter your name: ").strip()
print(f'Hello, {name}')

Enter your name: Reuven
Hello, Reuven


In [ ]:
# from the command line, install NumPy with
# pip3 install -U numpy 

# import numpy   # don't do this!

# the below is super-standard in data science
import numpy as np

In [25]:
# the below line loads NumPy as np (and does other things, too)
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [27]:
np.ndarray    # NumPy's n-dimensional array

numpy.ndarray

In [29]:
# don't run np.ndarray directly

# instead, use np.array!
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [30]:
type(a)

numpy.ndarray

In [31]:
a[0]

10

In [32]:
a[2]

30

In [33]:
a[-1]

50

In [34]:
a

array([10, 20, 30, 40, 50])

In [35]:
30 in a

True

In [36]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [37]:
a

array([10, 20, 30, 40, 50])