In [ ]:
# To install Jupyter, go to the command line (not inside of Python)
# and type

pip3 install -U jupyter
or
pip install -U jupyter

# then you should be able to type

jupyter notebook



In [1]:
# REPL -- read, eval, print loop

print('Hello, world!')  # shift + enter together == run the cell

Hello, world!


In [2]:
print('Hello, world!')
print('Hello, again!')

Hello, world!
Hello, again!


In [6]:
x = 100

In [7]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

In [8]:
# shift+enter runs a cell

In [9]:
# "magic" commands

# if the command starts with %, Jupyter "steals" it and runs it itself
%pwd

'/Users/reuven/Consulting/Courses/Data Science/cisco-2019-dec'

In [10]:
# ! before a command runs it in a shell

In [11]:
%whos  

Variable   Type    Data/Info
----------------------------
x          int     100


In [13]:
y = [10, 20, 30]

z = {'a':1, 'b':2, 'c':3}

def hello(name):
    return f'Hello, {name}'

In [14]:
%whos

Variable   Type        Data/Info
--------------------------------
hello      function    <function hello at 0x10fbacd40>
x          int         100
y          list        n=3
z          dict        n=3


In [15]:
%magic

In [16]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [17]:
print(x * 2)

200


In [18]:
# only in Jupyter, the final expression in a cell is returned
x

100

In [19]:
x*2

200

In [20]:
2+2
3+3
4+4

8

In [22]:
s = 'abcde'

In [23]:
s.upper()

'ABCDE'

In [24]:
# jupyter notebook 

# (1) Install and start Jupyter (if you haven't yet done so)
# (2) Start a new notebook
# (3) Rename the notebook (by clicking on the title)
# (4) Write a simple Python program that (a) asks the user
#     to enter their name and (b) prints Hello + the user's name
#     when this runs

name = input("Enter your name: ").strip()
print(f'Hello, {name}')

Enter your name: Reuven
Hello, Reuven


In [ ]:
# from the command line, install NumPy with
# pip3 install -U numpy 

# import numpy   # don't do this!

# the below is super-standard in data science
import numpy as np

In [25]:
# the below line loads NumPy as np (and does other things, too)
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [27]:
np.ndarray    # NumPy's n-dimensional array

numpy.ndarray

In [29]:
# don't run np.ndarray directly

# instead, use np.array!
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [30]:
type(a)

numpy.ndarray

In [31]:
a[0]

10

In [32]:
a[2]

30

In [33]:
a[-1]

50

In [34]:
a

array([10, 20, 30, 40, 50])

In [35]:
30 in a

True

In [36]:
for one_item in a:
    print(one_item)

10
20
30
40
50


In [37]:
a

array([10, 20, 30, 40, 50])

In [38]:
# simplest is np.array
np.array([10, 20, 30, 40, 50])



array([10, 20, 30, 40, 50])

In [40]:
# random integers -- use np.random.randint(max, min, count)
np.random.randint(0, 100, 10)

array([62,  6, 93,  3, 20, 58,  1, 77, 45, 35])

In [41]:
# random floats between 0-1 -- use np.random.rand(count)
np.random.rand(10)

array([0.10829865, 0.24817243, 0.46661636, 0.69170322, 0.21394568,
       0.70065355, 0.25283911, 0.55662296, 0.73601991, 0.23784385])

In [44]:
# I want a NumPy array with all numbers from 10-20
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10, 30, 4)

array([10, 14, 18, 22, 26])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
a

array([10, 20, 30, 40, 50])

In [50]:
# arrays are mutable!
a[2] = 12345
a

array([   10,    20, 12345,    40,    50])

In [51]:
# (1) Create a NumPy array with the integers from your birthdate (year,
#     month, and day)

a = np.array([1970, 7, 14])

In [52]:
# (2) Retrieve the year.
a[0]

1970

In [53]:
# (3) Replace the year with the current year.
a[0] = 2019
a

array([2019,    7,   14])

In [54]:
# (4) Create a NumPy array containing every 3rd number from 567 to
#     890. What is the 8th number in this array?  What is the 15th?

a = np.arange(567, 890, 3)
a[8]


591

In [55]:
a[15]

612

In [56]:
mylist = [10, 20, 30, 40, 50]
mylist + 60

TypeError: can only concatenate list (not "int") to list

In [57]:
mylist + mylist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [58]:
a = np.array([10, 20, 30 ,40, 50])
a + a

array([ 20,  40,  60,  80, 100])

In [59]:
# adding two arrays means adding each element at the same index

a - a

array([0, 0, 0, 0, 0])

In [60]:
a * a

array([ 100,  400,  900, 1600, 2500])

In [61]:
a / a

array([1., 1., 1., 1., 1.])

In [62]:
b = np.array([10, 20, 30, 40, 50, 60])

a + b

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [63]:
a

array([10, 20, 30, 40, 50])

In [65]:
a + 3 # this 'broadcasts' the scalar value and adds it to each in a

array([13, 23, 33, 43, 53])

In [66]:
a - 3

array([ 7, 17, 27, 37, 47])

In [67]:
a * 3

array([ 30,  60,  90, 120, 150])

In [68]:
a / 3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [69]:
a ** 3

array([  1000,   8000,  27000,  64000, 125000])

In [70]:
a % 3

array([1, 2, 0, 1, 2])

In [71]:
a

array([10, 20, 30, 40, 50])

In [72]:
# NumPy array methods:

a.sum()

150

In [73]:
a.mean()

30.0

In [74]:
a.std()

14.142135623730951

In [75]:
a.min()

10

In [76]:
a.max()

50

In [79]:
a.size  # not a method -- data giving us the size

5

In [82]:
# multiply the result from np.random.rand, and get
# numbers from 0 to that multiplied value

np.random.rand(10) * 100

array([10.69046194, 64.26513365, 28.10584285, 12.84197429, 30.90030687,
       39.10297485, 34.56071006, 96.01627624, 88.58263931, 17.35199359])

In [83]:
np.ones(10) * 8

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [84]:
np.zeros(10) + 8

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [85]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [86]:
# (1) Create an array of 10 random integers, from 0-100.

a = np.random.randint(0, 100, 10)
a

array([40, 49, 33, 10, 28, 36, 22, 32, 56, 73])

In [87]:
# (2) Find the mean and standard deviation of these numbers.  
a.mean()

37.9

In [88]:
a.std()

16.96732153287607

In [89]:
# (3) Create another array of 10 random integers, from 0-100.
b = np.random.randint(0, 100, 10)
b

array([50, 68, 58, 70, 89, 49, 71, 89, 30, 54])

In [90]:
# (4) Create a new 2-element array whose elements are
#     the average (mean) of those from exercises 1 and 3

c = np.array([a.mean(), b.mean()])
c

array([37.9, 62.8])

In [91]:
# (5) Create an array of 10 random floats, from 0-100.
a = np.random.rand(10) * 100
a

array([30.44166337, 79.58796334,  5.65226957, 54.31853198, 36.58045017,
       19.59407182, 43.14154103, 40.22547496, 18.49171147, 23.77969494])

In [92]:
# (6) We would expect the mean to be approaximately 50. 
#     Is it?  What's the standard deviation?
a.mean()

35.18133726559421

In [98]:
a = np.random.rand(100000) * 100
a.mean()

49.99103388595718

In [99]:
a.std()

28.870658854398407

In [100]:
# (7) What are the min and max values?
a.min()

0.0007180047562949099

In [101]:
a.max()

99.9988532801397

In [102]:
a = np.random.randint(0, 100, 10)
a

array([60, 69, 80, 48, 67, 89, 73, 64, 98, 92])

In [103]:
a[2]

80

In [104]:
a[6]

73

In [105]:
np.array([a[2], a[6]])

array([80, 73])

In [106]:
# fancy indexing
a[ [2, 6] ]

array([80, 73])

In [107]:
a

array([60, 69, 80, 48, 67, 89, 73, 64, 98, 92])

In [108]:
a[ [2, 6] ] = 1234
a

array([  60,   69, 1234,   48,   67,   89, 1234,   64,   98,   92])

In [109]:
a[ [2,3,2,3,2,3] ]

array([1234,   48, 1234,   48, 1234,   48])

In [110]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [111]:
a[2]

30

In [112]:
a[[2,4]]

array([30, 50])

In [113]:
# mask index -- wherever there is a True value, we get the value from a
a[[True, False, True, False, True]]

array([10, 30, 50])

In [114]:
a[[True, False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2

In [115]:
a

array([10, 20, 30, 40, 50])

In [116]:
a + 3  # this returns a new array; doesn't affect a at all

array([13, 23, 33, 43, 53])

In [117]:
a == 30

array([False, False,  True, False, False])

In [118]:
a < 30

array([ True,  True, False, False, False])

In [119]:
b = a < 30
a[b]   # show me elements of a where b is True (i.e., < 30)

array([10, 20])

In [120]:
a[a<30]  # using a boolean index to retrieve from a

array([10, 20])

In [121]:
a[a>20]

array([30, 40, 50])

In [122]:
a[a<1000]

array([10, 20, 30, 40, 50])

In [123]:
a[a>1000]

array([], dtype=int64)

In [124]:
a = 100
b = 100

a == b   # a.__eq__(b)

True

In [125]:
a

100

In [126]:
a = np.array([10, 20, 30, 40, 50])
a + 5

array([15, 25, 35, 45, 55])

In [127]:
a

array([10, 20, 30, 40, 50])

In [128]:
a += 5    # same as a = a + 5
a

array([15, 25, 35, 45, 55])

In [129]:
a

array([15, 25, 35, 45, 55])

In [130]:
a *= 3

In [131]:
a

array([ 45,  75, 105, 135, 165])

In [132]:
# += -= *= /= **= %= 

In [133]:
a = np.array([10, 15, 20, 25, 30, 35])
a

array([10, 15, 20, 25, 30, 35])

In [134]:
a % 2   # % ("modulus") is the remainder from integer division

array([0, 1, 0, 1, 0, 1])

In [135]:
a[a%2]  # this does NOT give us all odd elements

array([10, 15, 10, 15, 10, 15])

In [136]:
a[a%2 == 1]  # this *DOES* give us all odd elements

array([15, 25, 35])

In [137]:
a[a%2 == 0]  # gives me all even elements

array([10, 20, 30])

In [138]:
a[a%2 == 0] = 9999
a

array([9999,   15, 9999,   25, 9999,   35])

In [160]:
# control-shift-_ splits a cell into two at the current point
# there are menu items to merge cells above/below

# (1) Create an array of 20 random integers from 0 to 100.
a = np.random.randint(0, 100, 20)
a

array([96, 88,  9, 78, 46, 71, 33, 58, 39, 27, 22, 10, 81, 90, 42, 72, 81,
       14, 41, 93])

In [146]:
# (2) Find the largest even number.
a[a%2 == 0].max()

84

In [149]:
# (3) Find the mean of the odd numbers.
a[a%2 == 1].mean()

45.4

In [165]:
# (4) Create a 2-element NumPy array from the 
# first and last odd numbers.
a[a%2 == 1][[0,-1]]

array([ 9, 93])

In [153]:
# (5) Create an array of 20 floats from 0-1000.
a = np.random.rand(20) * 1000
a

array([705.79754313, 729.21798734, 776.31991389, 192.56154669,
       561.93438959, 112.65675346, 780.78093286,  54.1008814 ,
       596.75184718, 503.85032925,  48.51826974, 689.54483213,
       402.6134912 , 103.36685962, 703.7825231 , 673.87812785,
       414.43131241, 547.89545497, 113.4135059 , 859.88929099])

In [156]:
# (6) Find the items that are less than the mean.

a[a < a.mean()]   # show elements of a < a.mean()


array([192.56154669, 112.65675346,  54.1008814 ,  48.51826974,
       402.6134912 , 103.36685962, 414.43131241, 113.4135059 ])

In [157]:
# (7) Find the items less than mean-std.
a[a < a.mean()-a.std()]



array([192.56154669, 112.65675346,  54.1008814 ,  48.51826974,
       103.36685962, 113.4135059 ])

In [158]:
a[a > a.mean() + a.std()]


array([776.31991389, 780.78093286, 859.88929099])

In [142]:
a = np.random.randint(0, 100, 20)


In [170]:
# find even numbers that are greater than the mean

a = np.random.randint(0, 100, 10)
a

array([ 5, 20, 15, 67, 89, 74,  4, 36, 76, 57])

In [171]:
a[a%2 == 0]

array([20, 74,  4, 36, 76])

In [172]:
a[a>a.mean()]

array([67, 89, 74, 76, 57])

In [173]:
a[a%2 == 0 and a>a.mean()]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [174]:
x = 5

if x == 5:
    print("True!")

True!


In [175]:
if x:
    print("True!")
else:
    print("False!")

True!


In [176]:
# In Python, everything in a boolean context is True except for:
# - False
# - None
# - 0
# - anything empty

In [177]:
while True:
    name = input("Enter your name: ").strip()
    
    if not name:   # empty string is False in an "if" statement
        break
        
    print(f'Hello, {name}')

Enter your name: asdfa
Hello, asdfa
Enter your name: asdfadfa
Hello, asdfadfa
Enter your name: 


In [179]:
# return a new boolean array indicating where it's True in both
(a%2 == 0) & (a>a.mean())

array([False, False, False, False, False,  True, False, False,  True,
       False])

In [180]:
# return a new boolean array indicating where it's True in both
a[(a%2 == 0) & (a>a.mean())]

array([74, 76])

In [181]:
# to use more than one condition:
# - don't use "and" or "or".  Rather, use "&" and "|"
# - put your conditions inside of parentheses to reduce ambiguity
# - each individual condition should return a boolean array
# - & returns True where both arrays are True
# - | returns True where one array is True

In [182]:
a[(a%2 == 0) &
  (a>a.mean())]

array([74, 76])

In [183]:
# (1) Create a NumPy array of 20 random integers from 0-100.
a = np.random.randint(0, 100, 20)
a

array([ 7, 47, 53, 79, 62, 70, 80, 30,  2, 52, 48, 69, 13, 57, 73, 83,  6,
       26, 49, 82])

In [185]:
# (2) What's the smallest even number greater than the mean?
a[a > a.mean()]

array([53, 79, 62, 70, 80, 52, 69, 57, 73, 83, 82])

In [187]:
a[a%2 == 0]

array([62, 70, 80, 30,  2, 52, 48,  6, 26, 82])

In [191]:
a[(a>a.mean()) &
  (a%2==0)].min()

52

In [193]:
# (3) Show all numbers either <mean-std or >mean+std.
# meaning: find the outliers

a[a < a.mean() - a.std()]

array([ 7,  2, 13,  6])

In [195]:
a[a > a.mean() + a.std()]

array([79, 80, 83, 82])

In [197]:
a[(a < a.mean() - a.std()) |
  (a > a.mean() + a.std())]

array([ 7, 79, 80,  2, 13, 83,  6, 82])

In [201]:
# (4) Show odd numbers < mean and even numbers > mean.

a[(a%2 == 1) & (a < a.mean())   | (a%2 == 0) & (a > a.mean())]

array([ 7, 47, 62, 70, 80, 52, 13, 49, 82])

In [202]:
sorted(a[(a%2 == 1) & (a < a.mean())   |
         (a%2 == 0) & (a > a.mean())])

[7, 13, 47, 49, 52, 62, 70, 80, 82]

In [203]:
a

array([ 7, 47, 53, 79, 62, 70, 80, 30,  2, 52, 48, 69, 13, 57, 73, 83,  6,
       26, 49, 82])

In [205]:
a[(a%2==0) & (a>a.mean()) ] = 99999
a

array([    7,    47,    53,    79, 99999, 99999, 99999,    30,     2,
       99999,    48,    69,    13,    57,    73,    83,     6,    26,
          49, 99999])

In [206]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [207]:
a[2] = 234
a

array([ 10,  20, 234,  40,  50])

In [208]:
a[2] = 10.56

In [209]:
a

array([10, 20, 10, 40, 50])

In [210]:
int(10.56)

10

In [211]:
a[3] = '1234'

In [212]:
a

array([  10,   20,   10, 1234,   50])

In [213]:
a[3] = '1234a'

ValueError: invalid literal for int() with base 10: '1234a'

In [214]:
# dtype == the type of data that a NumPy array may contain

a

array([  10,   20,   10, 1234,   50])

In [215]:
# default dtype = np.int64

a.dtype

dtype('int64')

In [216]:
# the following 4 lines are all equivalent
np.int64
int64   # because %pylab inline imported it into the namespace

np.dtype('int64')
dtype('int64') # again, %pylab inline imported dtype

dtype('int64')

In [217]:
a = np.array([10, 20, 30, 40, 50], dtype=np.int8)
a

array([10, 20, 30, 40, 50], dtype=int8)

In [218]:
a + 100

array([ 110,  120, -126, -116, -106], dtype=int8)

In [219]:
a ** 3

array([-24,  64, 120,   0,  72], dtype=int8)

In [220]:
a

array([10, 20, 30, 40, 50], dtype=int8)

In [222]:
a.dtype = np.int16


ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.

In [223]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [224]:
a.dtype = np.int8

In [225]:
a

array([10,  0,  0,  0,  0,  0,  0,  0, 20,  0,  0,  0,  0,  0,  0,  0, 30,
        0,  0,  0,  0,  0,  0,  0, 40,  0,  0,  0,  0,  0,  0,  0, 50,  0,
        0,  0,  0,  0,  0,  0], dtype=int8)

In [226]:
a.dtype = np.float16

In [227]:
a

array([6.0e-07, 0.0e+00, 0.0e+00, 0.0e+00, 1.2e-06, 0.0e+00, 0.0e+00,
       0.0e+00, 1.8e-06, 0.0e+00, 0.0e+00, 0.0e+00, 2.4e-06, 0.0e+00,
       0.0e+00, 0.0e+00, 3.0e-06, 0.0e+00, 0.0e+00, 0.0e+00],
      dtype=float16)

In [228]:
a.dtype = np.int64
a

array([10, 20, 30, 40, 50])

In [229]:
a = np.array([10, 20, 30.5, 40, 50])
a

array([10. , 20. , 30.5, 40. , 50. ])

In [230]:
a.dtype

dtype('float64')

In [231]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float16)
a

array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float16)

In [232]:
a + 0.1

array([0.2   , 0.2998, 0.4   , 0.5   , 0.6   ], dtype=float16)

In [233]:
a + 0.2

array([0.2998, 0.4   , 0.5   , 0.5996, 0.7   ], dtype=float16)

In [234]:
1/3

0.3333333333333333

In [235]:
0.1 + 0.2

0.30000000000000004

In [236]:
0.1 + 0.2 == 0.3

False

In [237]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=np.float128)
a

array([0.1, 0.2, 0.3, 0.4, 0.5], dtype=float128)

In [238]:
a + 0.1

array([0.2, 0.3, 0.4, 0.5, 0.6], dtype=float128)

In [239]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [240]:
a.dtype

dtype('int64')

In [241]:
a.astype(np.float64)  # returns a new array with the new dtype

array([10., 20., 30., 40., 50.])

In [242]:
b = a.astype(np.float64)
b

array([10., 20., 30., 40., 50.])

In [243]:
b[1] = 33
b

array([10., 33., 30., 40., 50.])

In [244]:
a

array([10, 20, 30, 40, 50])

In [246]:
np.ones(10, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [247]:
a = np.array('this is a test'.split())


In [248]:
a

array(['this', 'is', 'a', 'test'], dtype='<U4')

In [249]:
a[0] = 'abcd'
a

array(['abcd', 'is', 'a', 'test'], dtype='<U4')

In [250]:
a[0] = 'abcdefgh'


In [251]:
a

array(['abcd', 'is', 'a', 'test'], dtype='<U4')

In [252]:
a.astype(np.int64)

ValueError: invalid literal for int() with base 10: 'abcd'

In [253]:
a = np.array(['10 20 30 40 50'.split()])
a

array([['10', '20', '30', '40', '50']], dtype='<U2')

In [254]:
a.astype(np.int64)

array([[10, 20, 30, 40, 50]])

In [255]:
# (1) Create a NumPy array of 10 random integers from 0-100.
a = np.random.randint(0, 100, 10)
a

array([50, 59, 18, 34, 17, 89, 69, 85, 29, 94])

In [256]:
# (2) Calculate the mean, which will be a float.
a.mean()

54.4

In [257]:
# (3) Create an array of type float based on ex (1),
#     and replace the outliers (i.e., <mean-std or 
#     >mean+std) with the mean (from ex 2).

b = a.astype(np.float64)
b

array([50., 59., 18., 34., 17., 89., 69., 85., 29., 94.])

In [260]:
a[(a < a.mean() - a.std()) | (a > a.mean() + a.std())] = a.mean()
a

array([50, 59, 54, 34, 54, 54, 69, 54, 29, 54])

In [261]:
b[(b < b.mean() - b.std()) | (b > b.mean() + b.std())] = a.mean()
b


array([50. , 59. , 51.1, 34. , 51.1, 51.1, 69. , 51.1, 29. , 51.1])

In [262]:
# (4) Create a NumPy array of 20 random floats from 0-100.
a = np.random.rand(20) * 100
a

array([56.5811093 , 22.08045686, 50.71188631, 50.04713333, 17.53508546,
       39.11959546,  4.05408988, 92.6956177 , 11.60379571, 72.12556634,
       50.24537108, 83.8305103 , 27.34618333, 44.31868001, 30.70523004,
       42.49172462, 49.78129828, 44.16441803, 15.81131309, 61.48642379])

In [263]:
# (5) Replace those numbers whose int portion is even with the mean.
#     (So 20.5 would be replaced, but 21.5 would not be.)

a[a%2 == 0]

array([], dtype=float64)

In [268]:
a[a.astype(np.int64) % 2 == 0]

array([56.5811093 , 22.08045686, 50.71188631, 50.04713333,  4.05408988,
       92.6956177 , 72.12556634, 50.24537108, 44.31868001, 30.70523004,
       42.49172462, 44.16441803])

In [269]:

a[a.astype(np.int64) % 2 == 0] = a.mean()
a

array([43.33677445, 43.33677445, 43.33677445, 43.33677445, 17.53508546,
       39.11959546, 43.33677445, 43.33677445, 11.60379571, 43.33677445,
       43.33677445, 83.8305103 , 27.34618333, 43.33677445, 43.33677445,
       43.33677445, 49.78129828, 43.33677445, 15.81131309, 61.48642379])

In [270]:
a

array([43.33677445, 43.33677445, 43.33677445, 43.33677445, 17.53508546,
       39.11959546, 43.33677445, 43.33677445, 11.60379571, 43.33677445,
       43.33677445, 83.8305103 , 27.34618333, 43.33677445, 43.33677445,
       43.33677445, 49.78129828, 43.33677445, 15.81131309, 61.48642379])

In [272]:
a[True] = 13

In [273]:
a

array([13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13., 13.,
       13., 13., 13., 13., 13., 13., 13.])

In [275]:
help(a.fill)

Help on built-in function fill:

fill(...) method of numpy.ndarray instance
    a.fill(value)
    
    Fill the array with a scalar value.
    
    Parameters
    ----------
    value : scalar
        All elements of `a` will be assigned this value.
    
    Examples
    --------
    >>> a = np.array([1, 2])
    >>> a.fill(0)
    >>> a
    array([0, 0])
    >>> a = np.empty(2)
    >>> a.fill(1)
    >>> a
    array([1.,  1.])



In [277]:
score = np.array([90, 85, 100, 92, 86])

score.mean()

90.6

In [278]:
score = np.array([90, 85, 100, 92, 0])

score.mean()

73.4

In [279]:
np.nan  #  "not a number"

nan

In [280]:
nan

nan

In [281]:
score

array([ 90,  85, 100,  92,   0])

In [282]:
score[-1] = nan

ValueError: cannot convert float NaN to integer

In [283]:
type(nan)

float

In [284]:
scores = np.array([90,  85, 100,  92,   nan])
scores

array([ 90.,  85., 100.,  92.,  nan])

In [285]:
scores.dtype

dtype('float64')

In [286]:
scores.mean()

nan

In [287]:
scores.sum()

nan

In [288]:
scores

array([ 90.,  85., 100.,  92.,  nan])

In [289]:
scores[scores != nan]

array([ 90.,  85., 100.,  92.,  nan])

In [290]:
nan == nan

False

In [291]:
np.isnan(nan)

True

In [292]:
np.isnan(5)

False

In [293]:
np.isnan(scores)

array([False, False, False, False,  True])

In [294]:
not np.isnan(scores)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [295]:
# in NumPy, we use & for "and"
# - we use | for "or"
# - we use ~ (tilde) for "not"

In [296]:
# return a boolean array indicating what is NOT a nan value
~np.isnan(scores)

array([ True,  True,  True,  True, False])

In [300]:
scores[~np.isnan(scores)].mean()

91.75

In [301]:
# (1) Create a NumPy array of 30 random ints from 0-1000.

a = np.random.randint(0, 1000, 30)
a

array([968, 988, 192, 736, 154, 800, 922, 535, 887,  64, 608, 284, 601,
       517, 619, 623, 877, 845, 157, 147, 227, 389, 280, 609, 515, 439,
        47, 547, 792, 786])

In [304]:
# (2) Find the numbers that are <mean-std or >mean+std, 
#     and set them to be nan

a = a.astype(np.float64)

In [305]:
a

array([968., 988., 192., 736., 154., 800., 922., 535., 887.,  64., 608.,
       284., 601., 517., 619., 623., 877., 845., 157., 147., 227., 389.,
       280., 609., 515., 439.,  47., 547., 792., 786.])

In [307]:
a[(a<a.mean()-a.std()) | (a>a.mean()+a.std())] = np.nan

In [308]:
a

array([ nan,  nan,  nan, 736.,  nan, 800.,  nan, 535.,  nan,  nan, 608.,
       284., 601., 517., 619., 623.,  nan,  nan,  nan,  nan,  nan, 389.,
       280., 609., 515., 439.,  nan, 547., 792., 786.])

In [312]:
# (Maybe you need to turn it into a bunch of floats to accomplish this)

# (3) Now change those nan values to be the mean of the array's
#     elements

a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [313]:
a

array([569.41176471, 569.41176471, 569.41176471, 736.        ,
       569.41176471, 800.        , 569.41176471, 535.        ,
       569.41176471, 569.41176471, 608.        , 284.        ,
       601.        , 517.        , 619.        , 623.        ,
       569.41176471, 569.41176471, 569.41176471, 569.41176471,
       569.41176471, 389.        , 280.        , 609.        ,
       515.        , 439.        , 569.41176471, 547.        ,
       792.        , 786.        ])

In [314]:
a.mean()

569.4117647058823

In [318]:
# ndarray -- n-dimensional
# 
a = np.array([[10, 20, 30],
             [40, 50, 60],
             [70, 80, 90],
             [100, 110, 120],
             [130, 140, 160]])
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120],
       [130, 140, 160]])

In [319]:
type(a)

numpy.ndarray

In [320]:
a.shape   

(5, 3)

In [321]:
a = np.random.randint(0, 100, 24)
a

array([97, 30, 15, 58, 37, 98, 42, 32, 60, 55, 56, 98, 13, 15, 13,  6, 59,
       70,  7, 98, 99, 22, 79, 55])

In [322]:
a.shape

(24,)

In [323]:
a.shape = (6,4)

In [324]:
a

array([[97, 30, 15, 58],
       [37, 98, 42, 32],
       [60, 55, 56, 98],
       [13, 15, 13,  6],
       [59, 70,  7, 98],
       [99, 22, 79, 55]])

In [325]:
a.shape = (12,2)
a

array([[97, 30],
       [15, 58],
       [37, 98],
       [42, 32],
       [60, 55],
       [56, 98],
       [13, 15],
       [13,  6],
       [59, 70],
       [ 7, 98],
       [99, 22],
       [79, 55]])

In [326]:
a.shape = (2,12)
a

array([[97, 30, 15, 58, 37, 98, 42, 32, 60, 55, 56, 98],
       [13, 15, 13,  6, 59, 70,  7, 98, 99, 22, 79, 55]])

In [327]:
a.shape = (5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [328]:
a.shape = (6,4)
a

array([[97, 30, 15, 58],
       [37, 98, 42, 32],
       [60, 55, 56, 98],
       [13, 15, 13,  6],
       [59, 70,  7, 98],
       [99, 22, 79, 55]])

In [329]:
a.reshape(4,6)

array([[97, 30, 15, 58, 37, 98],
       [42, 32, 60, 55, 56, 98],
       [13, 15, 13,  6, 59, 70],
       [ 7, 98, 99, 22, 79, 55]])

In [330]:
a

array([[97, 30, 15, 58],
       [37, 98, 42, 32],
       [60, 55, 56, 98],
       [13, 15, 13,  6],
       [59, 70,  7, 98],
       [99, 22, 79, 55]])

In [331]:
a[3]

array([13, 15, 13,  6])

In [332]:
a[1]

array([37, 98, 42, 32])

In [333]:
a[[1,3]]

array([[37, 98, 42, 32],
       [13, 15, 13,  6]])

In [334]:
a[3]

array([13, 15, 13,  6])

In [335]:
a[3][1] # don't do this!

15

In [336]:
a[3,1]

15

In [337]:
a

array([[97, 30, 15, 58],
       [37, 98, 42, 32],
       [60, 55, 56, 98],
       [13, 15, 13,  6],
       [59, 70,  7, 98],
       [99, 22, 79, 55]])

In [338]:
a[:, 1]  # all rows, column index 1

array([30, 98, 55, 15, 70, 22])

In [339]:
a[[2,3], 1]

array([55, 15])

In [340]:
a = np.random.randint(0, 100, 24).reshape(6,4)
a

array([[37, 88, 26, 66],
       [21, 46, 84, 12],
       [18, 90, 83, 29],
       [79, 47, 81, 58],
       [ 6, 57,  3, 58],
       [93, 69, 57, 81]])

In [341]:
a = np.random.randint(0, 100, [6,4])
a

array([[94, 16, 58, 10],
       [52, 67, 30, 23],
       [64, 91, 98, 43],
       [ 1, 93, 34, 52],
       [51, 71, 40, 41],
       [ 3, 84, 97, 92]])

In [342]:
a.sum()

1305

In [343]:
# axis 0 == the rows
# specifying axis 0 means: I want a new row
#   with values taken from the sum of each column

a.sum(axis=0)  # specify the axis, and get a new element in that axis

array([265, 422, 357, 261])

In [345]:
# axis 1 == the columns
# specifying axis 1 means: I want a new column
#   with values taken from the sum of each row

a.sum(axis=1) # give me a new column with the sum of each row

array([178, 172, 296, 180, 203, 276])

In [346]:
a.mean(axis=0)

array([44.16666667, 70.33333333, 59.5       , 43.5       ])

In [347]:
a

array([[94, 16, 58, 10],
       [52, 67, 30, 23],
       [64, 91, 98, 43],
       [ 1, 93, 34, 52],
       [51, 71, 40, 41],
       [ 3, 84, 97, 92]])

In [348]:
# np.sort is an inplace sort -- it changes the array!

a.sort(axis=0)  # each column is sorted, from smallest to biggest

In [349]:
a

array([[ 1, 16, 30, 10],
       [ 3, 67, 34, 23],
       [51, 71, 40, 41],
       [52, 84, 58, 43],
       [64, 91, 97, 52],
       [94, 93, 98, 92]])

In [350]:
a.sort(axis=1)  # each row is sorted, from smallest to biggest
a

array([[ 1, 10, 16, 30],
       [ 3, 23, 34, 67],
       [40, 41, 51, 71],
       [43, 52, 58, 84],
       [52, 64, 91, 97],
       [92, 93, 94, 98]])

In [351]:
# (1) Create a 2-dimensional NumPy array of 45 random integers,
# from 0-100.  9x5

# (2) Retrieve the elements at row index 2.
# (3) Retrieve the elements at column index 3.


a = np.random.randint(0, 100, [9,5])
a

array([[25, 29, 75, 68, 95],
       [87, 99, 62,  8, 62],
       [55, 90, 66, 87, 49],
       [61, 99, 57, 63, 28],
       [92, 87, 15, 29, 32],
       [61, 25, 56, 59, 62],
       [30, 32, 59, 82, 94],
       [11, 44, 68, 89, 30],
       [15,  0, 51, 15, 20]])

In [352]:
a[2]

array([55, 90, 66, 87, 49])

In [353]:
a[:, 3]

array([68,  8, 87, 63, 29, 59, 82, 89, 15])

In [354]:
# (4) Retrieve the elements at row indexes 1 and 4.
a[[1,4]]

array([[87, 99, 62,  8, 62],
       [92, 87, 15, 29, 32]])

In [356]:
a[1:5:3]  # slice -- from:until:step

array([[87, 99, 62,  8, 62],
       [92, 87, 15, 29, 32]])

In [357]:
# (5) Retrieve the elements at column indexes 1 and 4.
a[:, 1]

array([29, 99, 90, 99, 87, 25, 32, 44,  0])

In [358]:
a[:, 4]

array([95, 62, 49, 28, 32, 62, 94, 30, 20])

In [359]:
a[:, [1, 4]]

array([[29, 95],
       [99, 62],
       [90, 49],
       [99, 28],
       [87, 32],
       [25, 62],
       [32, 94],
       [44, 30],
       [ 0, 20]])

In [366]:
# (6) Get the mean of the even numbers in row index 4.

a[4][a[4] % 2 == 0].mean()


62.0

In [367]:
# (7) Get the mean of the odd numbers in column index 4.

a[:,4][a[:,4] % 2 == 1].mean()


72.0

In [368]:
a

array([[25, 29, 75, 68, 95],
       [87, 99, 62,  8, 62],
       [55, 90, 66, 87, 49],
       [61, 99, 57, 63, 28],
       [92, 87, 15, 29, 32],
       [61, 25, 56, 59, 62],
       [30, 32, 59, 82, 94],
       [11, 44, 68, 89, 30],
       [15,  0, 51, 15, 20]])

In [369]:
a.shape

(9, 5)

In [370]:
b = a.reshape(5,9)
b

array([[25, 29, 75, 68, 95, 87, 99, 62,  8],
       [62, 55, 90, 66, 87, 49, 61, 99, 57],
       [63, 28, 92, 87, 15, 29, 32, 61, 25],
       [56, 59, 62, 30, 32, 59, 82, 94, 11],
       [44, 68, 89, 30, 15,  0, 51, 15, 20]])

In [371]:
a[2,2] = 9999
a

array([[  25,   29,   75,   68,   95],
       [  87,   99,   62,    8,   62],
       [  55,   90, 9999,   87,   49],
       [  61,   99,   57,   63,   28],
       [  92,   87,   15,   29,   32],
       [  61,   25,   56,   59,   62],
       [  30,   32,   59,   82,   94],
       [  11,   44,   68,   89,   30],
       [  15,    0,   51,   15,   20]])

In [372]:
b

array([[  25,   29,   75,   68,   95,   87,   99,   62,    8],
       [  62,   55,   90, 9999,   87,   49,   61,   99,   57],
       [  63,   28,   92,   87,   15,   29,   32,   61,   25],
       [  56,   59,   62,   30,   32,   59,   82,   94,   11],
       [  44,   68,   89,   30,   15,    0,   51,   15,   20]])

In [374]:
a.copy()

array([[  25,   29,   75,   68,   95],
       [  87,   99,   62,    8,   62],
       [  55,   90, 9999,   87,   49],
       [  61,   99,   57,   63,   28],
       [  92,   87,   15,   29,   32],
       [  61,   25,   56,   59,   62],
       [  30,   32,   59,   82,   94],
       [  11,   44,   68,   89,   30],
       [  15,    0,   51,   15,   20]])

In [375]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [376]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [377]:
r1 = np.random.randint(0,1000,30)
r2 = r1.astype('float64')

In [378]:
r1

array([990, 832, 560, 620, 292, 956, 119, 323, 988, 935, 407, 567, 895,
       794, 557, 875, 431, 977, 466, 532, 374, 492, 565, 726, 383, 260,
       524, 847, 555, 363])

In [379]:
r2

array([990., 832., 560., 620., 292., 956., 119., 323., 988., 935., 407.,
       567., 895., 794., 557., 875., 431., 977., 466., 532., 374., 492.,
       565., 726., 383., 260., 524., 847., 555., 363.])

In [380]:
r2[((r2 < (r1.mean() - r1.std())) | 
    (r1 > (r1.mean() + r1.std())))] = np.nan

In [381]:
r2

array([ nan, 832., 560., 620.,  nan,  nan,  nan,  nan,  nan,  nan, 407.,
       567.,  nan, 794., 557.,  nan, 431.,  nan, 466., 532., 374., 492.,
       565., 726., 383.,  nan, 524., 847., 555., 363.])

In [384]:
r2[~np.isnan(r2)]  # ~ (tilde) negates np.isnan

array([832., 560., 620., 407., 567., 794., 557., 431., 466., 532., 374.,
       492., 565., 726., 383., 524., 847., 555., 363.])

In [385]:
r2[np.isnan(r2)]  # this finds all nan values... not very exciting

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [386]:
r2

array([ nan, 832., 560., 620.,  nan,  nan,  nan,  nan,  nan,  nan, 407.,
       567.,  nan, 794., 557.,  nan, 431.,  nan, 466., 532., 374., 492.,
       565., 726., 383.,  nan, 524., 847., 555., 363.])

In [388]:
# get the mean without nan
r2[~np.isnan(r2)].mean()

557.6315789473684

In [389]:
# find the locations with nan
r2[np.isnan(r2)]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [390]:
# replace nan with the non-nan mean

r2[np.isnan(r2)] = r2[~np.isnan(r2)].mean()

In [391]:
r2

array([557.63157895, 832.        , 560.        , 620.        ,
       557.63157895, 557.63157895, 557.63157895, 557.63157895,
       557.63157895, 557.63157895, 407.        , 567.        ,
       557.63157895, 794.        , 557.        , 557.63157895,
       431.        , 557.63157895, 466.        , 532.        ,
       374.        , 492.        , 565.        , 726.        ,
       383.        , 557.63157895, 524.        , 847.        ,
       555.        , 363.        ])

In [392]:
import pandas as pd
from pandas import Series, DataFrame

In [393]:
s = Series([10, 20 ,30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [394]:
s[1]

20

In [395]:
s[1:4]

1    20
2    30
3    40
dtype: int64

In [397]:
s[[1,4]]

1    20
4    50
dtype: int64

In [398]:
s.sum()

150

In [399]:
s.mean()

30.0

In [400]:
s[s<s.mean()]

0    10
1    20
dtype: int64

In [401]:
s[s>s.mean()+s.std()]

4    50
dtype: int64

In [402]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [403]:
s = Series([10, 20, 30, 40, 50],
          index=[100, 200, 300, 400, 500])
s

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [405]:
s[100]

10

In [406]:
s = Series([10, 20, 30, 40, 50],
          index=list('abcde'))
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [407]:
s['b']

20

In [409]:
s['a':'c']

a    10
b    20
c    30
dtype: int64

In [410]:
s = Series([10, 20, 30, 40, 50],
          index=[100, 200, 300, 400, 500])
s

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [412]:
s

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [415]:
s.loc[200:400]

200    20
300    30
400    40
dtype: int64

In [416]:
s

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [417]:
# retrieve from Pandas using:
# - just square brackets -- it'll use the index as best as possible
# - use .loc -- uses the index, allows for slices + fancy indexes
# - use .iloc -- uses the position, allows slices + fancy index

In [418]:
s

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [419]:
s.loc[400]

40

In [420]:
s.loc[200:400]

200    20
300    30
400    40
dtype: int64

In [421]:
s.iloc[3]

40